Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -123,7 +123,15 @@ jobs:
         
         ARGS="O=out ARCH=arm64 ${{ env.EXTRA_CMDS }}"
         
+        mkdir -p out
+
         make -j$(nproc --all) $ARGS ${DEVICE}_defconfig
+
+        if [ -f "out/.config" ]; then
+            echo "Successfully generated out/.config"
+        else
+            echo "Error: out/.config not found!" && exit 1
+        fi
 
         make -j$(nproc --all) $ARGS
         
